version: "3.3"
services:
  company-shorts-postgres:
    image: "postgres:15.1-alpine"
    container_name: company-shorts-postgres
    volumes: 
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped    
    ports:
      - "5432:5432" 